name: oryon
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - ca-certificates=2023.11.17=hbcca054_0
  - certifi=2023.11.17=pyhd8ed1ab_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=13.2.0=h807b86a_3
  - libgomp=13.2.0=h807b86a_3
  - libstdcxx-ng=11.2.0=h1234567_1
  - ncurses=6.4=h6a678d5_0
  - openssl=3.2.0=hd590300_0
  - pip=23.3.1=py38h06a4308_0
  - python=3.8.18=h955ad1f_0
  - readline=8.2=h5eee18b_0
  - setuptools=68.0.0=py38h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - wheel=0.41.2=py38h06a4308_0
  - xz=5.4.2=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
      - addict==2.4.0
      - aiohttp==3.9.1
      - aiosignal==1.3.1
      - ansi2html==1.8.0
      - antlr4-python3-runtime==4.9.3
      - appdirs==1.4.4
      - asttokens==2.4.1
      - async-timeout==4.0.3
      - attrs==23.1.0
      - av==11.0.0
      - backcall==0.2.0
      - blinker==1.7.0
      - braceexpand==0.1.7
      - charset-normalizer==3.3.2
      - click==8.1.7
      - clip==1.0
      - cloudpickle==3.0.0
      - comm==0.2.0
      - configargparse==1.7
      - contourpy==1.1.1
      - cycler==0.12.1
      - dash==2.14.2
      - dash-core-components==2.0.0
      - dash-html-components==2.0.0
      - dash-table==5.0.0
      - decorator==5.1.1
      - defusedxml==0.7.1
      - docker-pycreds==0.4.0
      - easydict==1.11
      - einops==0.7.0
      - executing==2.0.1
      - fastjsonschema==2.19.0
      - filelock==3.13.1
      - flask==3.0.0
      - fonttools==4.45.1
      - freetype-py==2.4.0
      - frozenlist==1.4.0
      - fsspec==2023.10.0
      - ftfy==6.1.3
      - fvcore==0.1.5.post20221221
      - gitdb==4.0.11
      - gitpython==3.1.40
      - groundingdino==0.1.0
      - hsluv==5.0.4
      - huggingface-hub==0.19.4
      - hydra==2.5
      - hydra-core==1.3.2
      - idna==3.6
      - igraph==0.11.3
      - imageio==2.33.0
      - importlib-metadata==6.8.0
      - importlib-resources==6.1.1
      - iopath==0.1.10
      - ipython==8.12.3
      - ipywidgets==8.1.1
      - itsdangerous==2.1.2
      - jedi==0.19.1
      - jinja2==3.1.2
      - joblib==1.3.2
      - jsonschema==4.20.0
      - jsonschema-specifications==2023.11.2
      - jupyter-core==5.5.0
      - jupyterlab-widgets==3.0.9
      - kiwisolver==1.4.5
      - lazy-loader==0.3
      - lightning==2.1.2
      - lightning-utilities==0.10.0
      - markupsafe==2.1.3
      - matplotlib==3.7.4
      - matplotlib-inline==0.1.6
      - mpmath==1.3.0
      - multidict==6.0.4
      - multiscaledeformableattention==1.0
      - nbformat==5.7.0
      - nest-asyncio==1.5.8
      - networkx==3.1
      - numpy==1.24.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.18.1
      - nvidia-nvjitlink-cu12==12.3.101
      - nvidia-nvtx-cu12==12.1.105
      - omegaconf==2.3.0
      - open3d==0.17.0
      - opencv-python==4.8.1.78
      - opencv-python-headless==4.9.0.80
      - packaging==23.2
      - pandas==2.0.3
      - parameterized==0.9.0
      - parso==0.8.3
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - pillow==10.1.0
      - pkgutil-resolve-name==1.3.10
      - platformdirs==4.0.0
      - plotly==5.18.0
      - plyfile==1.0.2
      - portalocker==2.8.2
      - prompt-toolkit==3.0.41
      - protobuf==4.25.1
      - psutil==5.9.6
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pycocoevalcap==1.2
      - pycocotools==2.0.7
      - pyglet==2.0.10
      - pygments==2.17.2
      - pyopengl==3.1.4
      - pyparsing==3.1.1
      - pypng==0.0.19
      - pyquaternion==0.9.9
      - pyrender==0.1.45
      - python-dateutil==2.8.2
      - pytorch-lightning==2.1.2
      - pytorchvideo==0.1.5
      - pytz==2023.3.post1
      - pywavelets==1.4.1
      - pyyaml==6.0.1
      - referencing==0.31.1
      - regex==2023.10.3
      - requests==2.31.0
      - retrying==1.3.4
      - rpds-py==0.13.2
      - safetensors==0.4.1
      - scikit-image==0.21.0
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - seaborn==0.13.1
      - sentry-sdk==1.38.0
      - setproctitle==1.3.3
      - six==1.16.0
      - smmap==5.0.1
      - stack-data==0.6.3
      - submitit==1.5.1
      - supervision==0.19.0rc2
      - sympy==1.12
      - tabulate==0.9.0
      - tenacity==8.2.3
      - termcolor==2.3.0
      - texttable==1.7.0
      - thop==0.1.1-2209072238
      - threadpoolctl==3.2.0
      - tifffile==2023.7.10
      - timm==0.9.12
      - tokenizers==0.15.0
      - tomli==2.0.1
      - torch==1.12.0+cu116
      - torchaudio==0.12.0
      - torchinfo==1.8.0
      - torchmetrics==1.2.0
      - torchvision==0.13.0+cu116
      - tqdm==4.66.1
      - traitlets==5.14.0
      - transformers==4.35.2
      - transforms3d==0.4.1
      - trimesh==4.0.7
      - triton==2.1.0
      - typing-extensions==4.8.0
      - tzdata==2023.3
      - urllib3==2.1.0
      - vispy==0.14.1
      - wandb==0.16.0
      - wcwidth==0.2.12
      - webdataset==0.2.85
      - werkzeug==3.0.1
      - widgetsnbextension==4.0.9
      - yacs==0.1.8
      - yapf==0.40.2
      - yarl==1.9.3
      - zipp==3.17.0
